### ISSUE TITLE
Actualización en COMPOSER

### ISSUE THREAD

**Issue by MrDavidChz** [phpcfdi/cfditopdf#1]
Hola.

Que gran aporte, lo podrias subir a Composer, al parecer el comando 

> composer require phpcfdi/cfditopdf

 no funciona porque no existe el paquete en COMPOSER.

Saludos y Gracias.

**Comment by eclipxe13** [comment]
De nada, no me había fijado que no estaba publicado en packagist. Espero tener tiempo de publicarlo durante la semana.

**Comment by eclipxe13** [comment]
Listo, mejor terminé hoy con esto. El proyecto tiene dos formas de trabajar, como CLI o como librería.

Si lo único que te interesa es la herramienta como un comando entonces puedes descargar https://github.com/phpcfdi/cfditopdf/releases/download/v0.2.1/cfditopdf.phar
O bien vía `git clone git@github.com:phpcfdi/cfditopdf.git`, luego `composer install` y puedes ejecutar `php bin/cfditopdf`

Si lo que te interesa es usar la librería entonces ya está activa la instalación vía `composer`.

Posteriormente voy a averiguar cómo automatizar el proceso de firmado del archivo phar para subir también el archivo asc a github y que se pueda instalar usando phive https://phar.io.
