### ISSUE TITLE
Comprobantes Pago > campo faltante en documentos relacionados

### ISSUE THREAD

**Issue by shnere** [phpcfdi/cfditopdf#10]
En los comprobantes de tipo pago, falta el tipo de cambio de los documentos relacionados, se llama `TipoCambioDR` en el XML y está en el nodo `pago10:DoctoRelacionado`.

Ejemplo del XML:

```xml
<cfdi:Complemento>
		<pago10:Pagos Version="1.0">
			<pago10:Pago CtaBeneficiario="X" CtaOrdenante="X" FechaPago="2021-01-15T12:00:00" FormaDePagoP="03" MonedaP="MXN" Monto="59026.79" RfcEmisorCtaBen="X RfcEmisorCtaOrd="X">
				<pago10:DoctoRelacionado Folio="X" IdDocumento="X" ImpPagado="2224.75" ImpSaldoAnt="2224.75" ImpSaldoInsoluto="0.00" MetodoDePagoDR="PPD" MonedaDR="USD" NumParcialidad="1" Serie="X" TipoCambioDR="0.050522" />
```

Asumo que se debe de agregar aquí https://github.com/phpcfdi/cfditopdf/blob/5c0ada7cc7b9895682acae239eda01dac59c2fa7/templates/generic.php#L296 .

**Comment by eclipxe13** [comment]
Gracias! Tienes razón, te interesa hacer un Pull Request ?

**Comment by shnere** [comment]
Sí, con gusto!

**Comment by eclipxe13** [comment]
Muchas gracias por tu contribución, sería muy bueno que pudiieras participar en nuestra comunidad en discord https://discord.gg/aFGYXvX
Creo que algunos de tus proyectos se podrían beneficiar con las experiencias que tenemos y viceversa.
