### ISSUE TITLE
Modificación de plantilla

### ISSUE THREAD

**Issue by alejandrogova1** [phpcfdi/cfditopdf#12]
Que tal, hay alguna opción para cambiar la plantilla generica?

Algo así como lo siguiente:

// create the converter
$template="empresa1";
$converter = new \PhpCfdi\CfdiToPdf\Converter(
    new \PhpCfdi\CfdiToPdf\Builders\Html2PdfBuilder()
);

$converter.template($template);

Saludos!

**Comment by alejandrogova1** [comment]
olvidalo hehe ya vi la documentación...

**Comment by eclipxe13** [comment]
Qué bien que lo encontraste
