### ISSUE TITLE
Conversion 3.3 to 4.0 pdf con complementos

### ISSUE THREAD

**Issue by migsot1982** [phpcfdi/cfditopdf#14]
Hola amigos, una pregunta!, han logrado actualizar esta libreria a 4.0 con los detalles nuevos del pdf en complementos?

**Comment by eclipxe13** [comment]
Aún no se han hecho los cambios a las plantillas.
Como recomendación, podrías intentar con [nodecfdi/cfdi-to-pdf](https://github.com/nodecfdi/cfdi-to-pdf) en lo que esta librería se actualiza.
Estamos abiertos a las contribuciones que deseen hacer al código para convertir también CFDI 4.0

**Comment by AleksSamaniego** [comment]
Sabrán si hay alguna librería similar para .net?

**Comment by eclipxe13** [comment]
Me parece que no, pero puedes ejecutarla via command line o con docker
