### ISSUE TITLE
Error al instalar vía composer junto al módulo de timbrado

### ISSUE THREAD

**Issue by JHdezC** [phpcfdi/cfditopdf#2]
Estuve probando la librería para timbrar los xml y todo funciona bien, pero cuando quise instalar cfditopdf me salen muchos errores, con la librería eclipse/cfdiutils adjunto una captura con los errores que me salen.
Cree un proyecto de prueba donde instalé primero cfditopdf y luego la librería de timbrado pero ocurre el mismo error.
![Sin título](https://user-images.githubusercontent.com/47069970/61719745-15a75e80-ad2b-11e9-9b9c-3f7ab190332a.jpg)

**Comment by eclipxe13** [comment]
Saludos, no me di cuenta de este issue, todavía lo tienes ?

Al parecer es porque en tu composer.json estás usando una versión `dev-master` en lugar de las estables.
